'use client'
import {useState} from 'react'
import {useAccounts} from '@/hooks/use-finance'
import {useFinancialModel,useHistoricalRates} from '@/hooks/use-financial-model'
import {FinancialTrends} from '@/components/reports/financial-trends'
import {reportQuality,countedActual} from '@/lib/money/statistical'
import {periodCoverage} from '@/lib/calculations/history'
import Link from 'next/link'
import {ChevronRight} from 'lucide-react'
import {Input} from '@/components/ui/Input'
import {SegmentedControl} from '@/components/ui/segmented'
import {PeriodSummary} from '@/components/reports/period-summary'
import {PeriodControl} from '@/components/reports/period-control'
import {InfoButton,Money,Disclosure} from '@/components/ui/finance-visuals'
import {useWorkspaceContext} from '@/contexts/workspace-context'
import {useCategories,useTransactions} from '@/hooks/use-finance'
import {monthlyTotals,spendingByCategory,yearlyCashflow} from '@/lib/calculations/reports'
import {localDay,monthEnd} from '@/lib/calculations/dates'
import {categoryTransactionsUrl} from '@/lib/planning/model'
import {formatMoney} from '@/lib/money/format'
export default function ReportsPage(){
 const [month,setMonth]=useState(localDay().slice(0,7)),[view,setView]=useState<'month'|'year'>('month'),[year,m]=month.split('-').map(Number),{displayCurrency}=useWorkspaceContext(),{data:transactions=[],isLoading}=useTransactions(),{data:categories=[]}=useCategories()
 const {data:accounts=[]}=useAccounts(),model=useFinancialModel(),fx=useHistoricalRates(transactions.filter(t=>t.transactionDate.startsWith(String(year))),displayCurrency),options={rates:fx.data||[]},quality=reportQuality(transactions,displayCurrency,view==='month'?month:String(year),options)
 const qualityForMonth=(value:string)=>reportQuality(transactions,displayCurrency,value,options)
 const today=localDay(),coverage=model.data?.coverage||[],monthComplete=(value:string)=>value+'-01'<=today&&periodCoverage(accounts,coverage,value+'-01',monthEnd(value)<today?monthEnd(value):today).complete
 const actual=transactions.filter(t=>countedActual(t)),hasMonth=monthComplete(month)||actual.some(t=>t.transactionDate.startsWith(month)),totals=monthlyTotals(transactions,year,m-1,displayCurrency,options),byCategory=spendingByCategory(transactions,categories,year,m-1,displayCurrency,options),trend=yearlyCashflow(transactions,year,displayCurrency,options),yearly=trend.reduce((a,p)=>({income:a.income+p.income,expense:a.expense+p.expense,net:a.net+p.net}),{income:0,expense:0,net:0}),hasYear=trend.some(p=>monthComplete(year+'-'+String(p.month0+1).padStart(2,'0')))||actual.some(t=>t.transactionDate.startsWith(String(year)+'-')),shown=view==='month'?totals:yearly,hasData=view==='month'?hasMonth:hasYear,maximum=Math.max(1,...trend.flatMap(p=>[p.income,p.expense]))
 if(isLoading||fx.isLoading||model.isLoading)return <div className="finance-skeleton" role="status">Рахуємо статистику…</div>
 let arcOffset=0
 return <div className="finance-page"><header className="finance-page-heading"><div><p className="finance-eyebrow">Доходи та витрати</p><h1>Статистика</h1></div><InfoButton title="Як читати статистику"><p>Доходи мінус повні витрати сімейного бюджету за період. Оплата кредиту входить у витрати повною сумою, без розподілу на тіло та комісії. Купівля з кредитки є витратою, поповнення кредитки не повторює її. Перекази між своїми рахунками не враховуються. Початкові залишки не є доходом. Результат періоду не є залишком грошей на рахунках.</p></InfoButton></header><div className="report-controls"><SegmentedControl aria-label="Період статистики" value={view} onChange={setView} options={[{value:'month',label:'Місяць'},{value:'year',label:'Рік'}]}/><Input type="month" aria-label="Місяць і рік статистики" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></div>
 <div className="reports-grid"><PeriodSummary title={view==='month'?'Результат місяця':year+' рік'} totals={shown} currency={displayCurrency} hasData={hasData} quality={quality} coverageComplete={view==='month'?monthComplete(month):periodCoverage(accounts,coverage,year+'-01-01',year+'-12-31'<today?year+'-12-31':today).complete}><Disclosure title={hasData?'Що враховано у звіті':'Чому тут не нуль'}><p>{hasData?'Обчислено за виконаними транзакціями та курсами на їхні дати. Повноту періоду можна підтвердити в налаштуваннях.':'Відсутність внесених операцій не означає, що реальних витрат чи доходів не було.'} Початковий залишок не включається в дохід.</p></Disclosure></PeriodSummary>
 {view==='month'?<section className="finance-surface category-report"><div className="finance-card-heading"><h2>Куди пішли гроші</h2><span className="finance-caption">{byCategory.length} категорій</span></div>{!byCategory.length?<div className="finance-empty"><strong>{quality.incomplete?'Витрати потребують уточнення':'Поки немає витрат'}</strong><span>{quality.incomplete?'Перевірте історичні курси валют.':'Категорії з’являться після додавання операцій.'}</span></div>:<><div className="expense-donut"><svg viewBox="0 0 160 160" role="img" aria-label={'Витрати за категоріями, всього '+formatMoney(totals.expense,displayCurrency)}><circle cx="80" cy="80" r="62" fill="none" stroke="var(--border-glass)" strokeWidth="17"/>{byCategory.map(c=>{const offset=arcOffset;arcOffset+=c.pct;return <circle key={c.categoryId||'none'} cx="80" cy="80" r="62" pathLength="100" fill="none" stroke={c.color} strokeWidth="17" strokeDasharray={Math.max(0,c.pct-.6)+' '+(100-Math.max(0,c.pct-.6))} strokeDashoffset={-offset} transform="rotate(-90 80 80)"/>})}</svg><div><strong>{formatMoney(totals.expense,displayCurrency,{compact:true})}</strong><small>{quality.incomplete?'відомі витрати':quality.estimated.length?'витрати ≈':'витрачено'}</small></div></div><ul className="category-legend">{byCategory.map(c=><li key={c.categoryId||'none'}><Link className="category-drilldown" aria-label={'Операції: '+c.name+', '+month} href={categoryTransactionsUrl(c.categoryId,month)}><span className="category-dot" style={{background:c.color}}/><span className="category-name">{c.name}<small>{Math.round(c.pct)}%</small></span><Money value={c.total} currency={displayCurrency}/><ChevronRight size={15}/></Link></li>)}</ul></>}</section>:<section className="finance-surface annual-report"><div className="finance-card-heading"><h2>Рік у цифрах</h2><span className="finance-caption">{year}</span></div><div className="chart-legend"><span><i className="legend-income"/>Доходи</span><span><i className="legend-expense"/>Витрати</span></div><div className="annual-bars" role="img" aria-label={'Доходи та витрати за місяцями '+year+' року. Точні суми наведені нижче.'}>{trend.map(p=>{const monthKey=year+'-'+String(p.month0+1).padStart(2,'0'),exists=monthComplete(monthKey)||actual.some(t=>t.transactionDate.startsWith(monthKey));return <div className="annual-bar-column" key={p.month0}><div className={'annual-bar-pair '+(!exists?'annual-bar-pair--empty':'')} title={p.monthName+': '+(exists?'дохід '+formatMoney(p.income,displayCurrency)+', витрати '+formatMoney(p.expense,displayCurrency):'немає даних')}><i style={{height:exists?p.income/maximum*100+'%':'0%'}}/><i style={{height:exists?p.expense/maximum*100+'%':'0%'}}/></div><span>{p.monthName.replace('.','').slice(0,3)}</span></div>})}</div><p className="finance-caption mt-3">Пунктир: немає історії. Для неповних місяців показані лише відомі суми; кредитні платежі входять повною сумою. Поточний місяць ще триває.</p></section>}</div>
 {view==='year'&&<section className="finance-surface mt-4"><div className="finance-card-heading"><h2>По місяцях</h2><span className="finance-caption">Відкрити деталі</span></div><div className="month-result-list">{trend.map(p=>{const monthKey=year+'-'+String(p.month0+1).padStart(2,'0'),exists=monthComplete(monthKey)||actual.some(t=>t.transactionDate.startsWith(monthKey)),monthQuality=qualityForMonth(monthKey);return <button key={p.month0} type="button" onClick={()=>{setMonth(year+'-'+String(p.month0+1).padStart(2,'0'));setView('month')}}><span className="month-result-name">{p.monthName}<small>{exists?'+'+formatMoney(p.income,displayCurrency)+' / −'+formatMoney(p.expense,displayCurrency):'Немає даних'}</small></span>{exists&&(monthQuality.incomplete?<span className="finance-caption">Неповні дані</span>:<span className="flex items-center gap-1">{monthQuality.estimated.length>0&&'≈'}<Money value={p.net} currency={displayCurrency} signed className={!monthQuality.provisional&&p.net>=0?'money-good':''}/></span>)}<ChevronRight size={16}/></button>})}</div></section>}<FinancialTrends currency={displayCurrency}/>{(model.isError||fx.isError)&&<p role="alert" className="finance-caption">Частину даних не завантажено. Підсумки можуть бути неповними.</p>}<Disclosure title="Керування місяцем"><PeriodControl month={month}/></Disclosure></div>
}
