
export type Schema = {type?:string|string[];properties?:Record<string,Schema>;required?:string[];additionalProperties?:boolean|Schema;items?:Schema;enum?:unknown[];minimum?:number;maximum?:number;minLength?:number;maxLength?:number;minItems?:number;maxItems?:number;pattern?:string;format?:string;description?:string;multipleOf?:number}
export type Tool = {name:string;title:string;description:string;inputSchema:Schema;readOnly:boolean;operation?:string;resource?:string;destructive?:boolean}
const text=(max=500):Schema=>({type:'string',maxLength:max})
const uuid:Schema={type:'string',format:'uuid'}
const date:Schema={type:'string',format:'date',description:'Calendar date YYYY-MM-DD, Europe/Kyiv.'}
const timestamp:Schema={type:'string',format:'date-time',description:'Use the exact updated_at returned by the server; preserve microseconds.'}
const money:Schema={type:'number',minimum:0.01,maximum:999999999999.99,multipleOf:0.01,description:'Positive amount in major currency units, at most two decimal places.'}
const nonnegative:Schema={...money,minimum:0}
const signed:Schema={...money,minimum:-999999999999.99,description:'Signed balance in major units. Debt is negative; available credit is not the balance.'}
const currency:Schema={type:'string',enum:['UAH','USD','EUR','GBP','PLN']}
const bool:Schema={type:'boolean'}
const nullable=(s:Schema):Schema=>({...s,type:[...(Array.isArray(s.type)?s.type:[s.type||'string']),'null']})
const object=(properties:Record<string,Schema>,required:string[]=[]):Schema=>({type:'object',properties,required,additionalProperties:false})
const page={limit:{type:'integer',minimum:1,maximum:200} as Schema,offset:{type:'integer',minimum:0,maximum:100000} as Schema}
const version:Schema={type:'string',pattern:'^[a-f0-9]{64}$',description:'Copy _version from the most recent read; do not invent it.'}
const values=(properties:Record<string,Schema>,required:string[]=[])=>object(properties,required)
const txFields={loan_account_id:nullable(uuid),loan_installment_id:nullable(uuid),accounting_class:{type:'string',enum:['ordinary','principal']} as Schema,forecast_behavior:{type:'string',enum:['auto','scheduled','one_off']} as Schema,flow_key:nullable(text(120)),planned_time:nullable({type:'string',pattern:'^([01][0-9]|2[0-3]):[0-5][0-9]$'}),plan_exchange_mode:nullable({type:'string',enum:['nbu','manual']}),plan_exchange_rate:nullable({type:'number',minimum:0.00000001,maximum:999999}),plan_exchange_date:nullable(date),account_id:uuid,counter_account_id:nullable(uuid),counter_amount:nullable(money),category_id:nullable(uuid),transaction_type_id:nullable(uuid),kind:{type:'string',enum:['income','expense','transfer']} as Schema,amount:money,currency,original_amount:nullable(money),original_currency:nullable(currency),description:{...text(120),minLength:1},notes:nullable(text(8000)),transaction_date:date,status:{type:'string',enum:['completed','planned']} as Schema,planned_date:nullable(date),occurred_at:nullable(text(60)),balance_treatment:{type:'string',enum:['auto','new_activity'],description:'auto protects historical/current balance anchors. new_activity only for a new purchase not already in the current snapshot.'} as Schema}
const accountFields={is_savings:bool,name:{...text(60),minLength:1},type:{type:'string',enum:['cash','bank_debit','savings','crypto','investment','receivable','credit_card','bank_loan','microloan','personal_debt','mortgage']} as Schema,currency,institution:nullable(text(80)),counterparty:nullable(text(80)),principal:nullable(nonnegative),interest_rate:nullable({type:'number',minimum:0,maximum:1000}),credit_limit:nullable(nonnegative),due_date:nullable(date),owner_user_id:nullable(uuid),is_shared:bool}
const categoryFields={include_in_daily_forecast:{...bool,description:'Include this category in automatic daily spending estimates. Does not remove explicit plans or change reports or reserve categories.'},is_essential:bool,name:{...text(40),minLength:1},type:{type:'string',enum:['income','expense']} as Schema,color:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'} as Schema,icon:{...text(40),minLength:1}}
const ruleFields={name:{...text(100),minLength:1},category_id:uuid,description_contains:{...text(200),minLength:1},is_active:bool,kind:nullable({type:'string',enum:['income','expense']}),min_amount:nullable(nonnegative),max_amount:nullable(nonnegative),account_id:nullable(uuid),priority:{type:'integer',minimum:0,maximum:10000} as Schema}
const loanFields={balance_basis:{enum:['principal','estimated_principal','total_obligation','unknown']},schedule_basis:{enum:['bank','estimated','unknown']},tracking_start_date:date,origination_date:nullable(date),payment_account_id:nullable(uuid),payoff_quote:nullable(nonnegative),payoff_quote_date:nullable(date),card_minimum:nullable(nonnegative),card_grace_amount:nullable(nonnegative),card_planned_amount:nullable(nonnegative),card_due_date:nullable(date),card_statement_date:nullable(date),notes:nullable(text(8000))}
const duplicateResolution=object({choice:{type:'string',enum:['existing','separate']},transaction_id:uuid,candidate_version:version,reason:{type:'string',minLength:12,maxLength:500,description:'Evidence from the user-provided source. Never invent a reason or classify identical amounts alone as the same purchase.'}},['choice','candidate_version','reason'])
const request={request_id:{...uuid,description:'Unique UUID idempotency key. Reuse the same key only when retrying exactly the same action and arguments.'}}
export const tools:Tool[]=[]
const read=(name:string,title:string,description:string,properties:Record<string,Schema>={},required:string[]=[],resource?:string)=>tools.push({name,title,description,inputSchema:object(properties,required),readOnly:true,resource})
const write=(name:string,title:string,description:string,properties:Record<string,Schema>,required:string[],operation=name,destructive=false)=>tools.push({name,title,description:description+' Executes directly with an active read/write connection, without a Forma approval page. Never claim a write succeeded unless status is completed and applied is true. needs_resolution means no mutation; resolve from source evidence using MCP, not an approval link.',inputSchema:object({...properties,...request},[...required,'request_id']),readOnly:false,operation,destructive})
read('get_context','Мій сімейний простір','Get the connected user, family, current permissions, currency conventions and capability limits.')
read('get_model_history','Історія моделі','Read declared account history coverage, recorded positions and immutable forecast snapshots. Missing days are not zero. No writes.')
write('confirm_history','Підтвердити повноту історії','Only after the user confirms all transactions for an account/date range are entered, including zero-activity days. Balance reconciliation alone is not evidence. Manager/owner only.',{account_ids:{type:'array',items:uuid,minItems:1,maxItems:200},from:date,to:date,kind:{type:'string',enum:['complete','no_activity','not_open']}},['account_ids','from','to','kind'])
const readResources:Array<[string,string,string]>=[['accounts','Рахунки','accounts'],['categories','Категорії','categories'],['category_rules','Правила категоризації','rules'],['transaction_types','Типи операцій','types'],['members','Учасники сім’ї','members'],['imports','Історія виписок','imports'],['loans','Кредити','loans'],['loan_imports','Історія графіків','loan_imports'],['resolutions','Виправлення дублів і переказів','resolutions'],['bulk_history','Масові зміни','bulk_history'],['periods','Закриті місяці','periods'],['recurring','Повторювані шаблони','recurring'],['expected','Очікувані операції','expected'],['ai_requests','Дії AI','requests']]
for(const [name,title,resource] of readResources)read('list_'+name,title,'List '+title+'. Paginated; follow nextOffset to avoid silently omitting records.',{...page,...(['imports','loans','loan_imports'].includes(resource)?{account_id:uuid}:{}),...(resource==='accounts'?{include_archived:bool}:{})},[],resource)
read('get_settings','Мої налаштування','Get personal defaults, favorite accounts, display currency and safety-buffer days.',{},[],'settings')
read('get_account','Рахунок і залишок','Get one account, signed balance, balance anchor and ledger_version.',{id:uuid},['id'],'accounts')
read('get_transaction','Операція','Read before editing. Returns updated_at and independent category review / balance verification status.',{id:uuid,include_deleted:bool},['id'],'transactions')
read('list_transactions','Операції','Search operations by account, category, date, import and review state. Recurring plans are ordinary planned transactions; paused plans are excluded. Foreign plans expose original_amount/original_currency and estimated_account_amount using current NBU or manual rates. Transfers are not income or expense.',{...page,account_id:uuid,category_id:uuid,uncategorized:bool,kind:txFields.kind,status:txFields.status,from:date,to:date,search:text(200),include_deleted:bool,needs_review:bool,import_batch_id:uuid},[],'transactions')
read('list_loan_schedule','Графік кредиту','Read the imported schedule. Historical or scheduled rows are not proof of actual payment.',{...page,account_id:uuid},['account_id'],'schedule')
read('list_balance_history','Історія звірок','Read balance confirmations independently of category review.',{...page,account_id:uuid},['account_id'],'balance_history')
write('cancel_request','Скасувати невиконаний запит AI','Cancel an obsolete request belonging to this connection. Does not undo completed actions.',{id:uuid},['id'])
read('get_request','Стан дії AI','Check whether a prepared action is completed, needs_resolution, cancelled, legacy pending or expired. No new action needs a Forma approval link.',{id:uuid},['id'],'requests')
read('get_month_report','Результат місяця','Household budget income minus full expenses. Non-card loan payments count in full under their category. Own transfers and credit-card top-ups are not expenses. Loan links never calculate debt; confirm the bank payoff balance separately. Missing historical FX is disclosed.',{month:{type:'string',pattern:'^\\d{4}-(0[1-9]|1[0-2])$'},currency},['month'])
read('get_year_report','Результат року','Get monthly and annual earned income and consumption totals, using transaction-date FX. Principal, own transfers and card top-ups are excluded. Uncertain loan allocation is disclosed.',{year:{type:'integer',minimum:1900,maximum:2200},currency},['year'])
read('get_forecast','Прогноз залишку','Forecast from explicitly created planned transactions and preliminary or confirmed spending history, matching Forma UI. Loan schedules have no effect. Not a guaranteed balance.',{through:date,currency},['through'])
read('get_reconciliation','Стан звірки','Get category review queue and independently unconfirmed balances for accounts.',{account_id:uuid})
read('explain_balance_difference','Підказки до розбіжності','Find operations that may explain a signed balance difference. Hints are not proof and never cause automatic corrections.',{account_id:uuid,actual_balance:signed},['account_id','actual_balance'])
read('find_transfer_pairs','Можливі власні перекази','Find matching outgoing/incoming entries across own accounts. Review before pairing.',{from:date,to:date})
read('get_import','Один імпорт','Get the statement batch and a versioned snapshot needed to safely move it to a different account.',{id:uuid},['id'])
const statementRow=object({date,amount:signed,description:{...text(120),minLength:1},occurred_at:nullable(text(60)),bank_reference:text(200),matched_transaction_id:nullable(uuid),match_updated_at:nullable(timestamp)},['date','amount','description'])
const statementInput={account_id:uuid,preview_offset:{type:'integer',minimum:0,maximum:5000} as Schema,resolutions:{type:'array',maxItems:5000,items:object({row:{type:'integer',minimum:1,maximum:5000},choice:{type:'string',enum:['new','skip','match']},transaction_id:uuid,expected_updated_at:timestamp,candidate_version:version,reason:{type:'string',minLength:12,maxLength:500}},['row','choice'])} as Schema,csv:{...text(2000000),description:'CSV text with date,description,amount. Negative = expense, positive = income. Alternatively supply rows.'},rows:{type:'array',items:statementRow,minItems:1,maxItems:5000} as Schema,file_name:text(200),mapping:object({date:{type:'integer',minimum:0,maximum:100},description:{type:'integer',minimum:0,maximum:100},amount:{type:'integer',minimum:0,maximum:100}},['date','description','amount'])}
read('preview_statement','Перевірити виписку','Parse CSV or normalized rows and show invalid rows, dates, account and potential duplicates among all existing manual/imported entries. Supply exactly one of csv or rows. Never merges guesses. For choice=new on a suspicious row, include the candidate_version from preview and an evidence-based reason. For already-imported entries, skip rather than match.',statementInput,['account_id'])
write('import_statement','Імпортувати виписку','Import validated CSV or normalized rows. Supply exactly one of csv or rows. Preserves balance anchors and repeated genuine payments. Exact import keys are skipped; unresolved candidates are returned without writing.',statementInput,['account_id'])
read('preview_loan_schedule','Перевірити графік кредиту','Parse a paper/PDF schedule already transcribed to CSV. Never assumes historical schedule rows were paid.',{account_id:uuid,csv:text(2000000)},['account_id','csv'])
write('import_loan_schedule','Імпортувати графік кредиту','Import a reference schedule inside the loan only. Does not create transactions, change balances or affect statistics/forecast. Existing future schedule may be superseded, never marked paid.',{account_id:uuid,csv:text(2000000),file_name:text(200)},['account_id','csv'])
const createValues=values(txFields,['account_id','kind','amount','currency','description','transaction_date'])
read('preview_transaction','Перевірити операцію на дубль','Read-only duplicate check against manual and imported transactions, including own-transfer legs. create_transaction rechecks atomically even if this preview is skipped. Use the same values when reusing candidate_version.',{values:createValues,bank_reference:text(200)},['values'],'transaction_duplicates')
write('save_recurring','Зберегти повторюваний план','Create or update an income/expense recurring series. New: values.template, frequency and start_date are required. Update: pass id and exact expected_updated_at; is_active alone pauses/resumes future plans. Existing source_transaction_id + source_expected_updated_at creates from an operation without duplicating it. A completed source is never changed. Occurrences are planned, never automatically completed. Individual edits/deletions survive regeneration. Monthly day 31 clamps to month end without drift. Time uses Europe/Kyiv. For a foreign plan keep amount/currency in the account currency and original_amount/original_currency in the contractual currency, with plan_exchange_mode nbu or manual and plan_exchange_rate (account currency per one original unit). Current NBU is an estimate, not a future exchange-rate forecast.',{id:uuid,expected_updated_at:timestamp,values:object({template:object({account_id:uuid,category_id:nullable(uuid),transaction_type_id:nullable(uuid),kind:{type:'string',enum:['income','expense']},amount:money,currency,original_amount:nullable(money),original_currency:nullable(currency),description:{...text(120),minLength:1},notes:nullable(text(500)),plan_exchange_mode:txFields.plan_exchange_mode,plan_exchange_rate:txFields.plan_exchange_rate,plan_exchange_date:txFields.plan_exchange_date,planned_time:txFields.planned_time},['account_id','kind','amount','currency','description']),frequency:{type:'string',enum:['daily','weekly','monthly','yearly']},interval_count:{type:'integer',minimum:1,maximum:120},start_date:date,end_date:nullable(date),is_active:bool,source_transaction_id:uuid,source_expected_updated_at:timestamp})},['values'])
write('create_transaction','Додати операцію','Create one expense, income, cash purchase, planned transaction or own-account transfer. Server checks duplicates before every insert. A stable bank_reference must come from the bank, never an invented identifier. Potential matches require evidence-based duplicate_resolution; identical amounts alone are not duplicates. existing reuses a record without editing it; separate preserves a real distinct purchase.',{values:createValues,bank_reference:text(200),duplicate_resolution:duplicateResolution},['values'])
write('update_transaction','Змінити транзакцію','Read the current record and preserve expected_updated_at. loan_account_id links a planned or completed expense to a debt; null detaches it. Category is independent. No principal or interest allocation is needed. Attaching a transfer directed to that loan converts the same record to an expense without a second debit.',{id:uuid,expected_updated_at:timestamp,values:values(txFields)},['id','expected_updated_at','values'])
for(const name of ['delete_transaction','restore_transaction'])write(name,name==='delete_transaction'?'Видалити операцію':'Відновити операцію','Soft-delete or restore one operation using its exact current version.',{id:uuid,expected_updated_at:timestamp},['id','expected_updated_at'],name,true)
write('review_transaction','Підтвердити перевірку операції','Confirm category review only. Does not confirm the account balance.',{id:uuid,expected_updated_at:timestamp},['id','expected_updated_at'])
write('classify_transaction','Категорія і правило','Set category and optionally create a description-matching automation rule. This is not bank balance reconciliation.',{id:uuid,category_id:uuid,expected_updated_at:timestamp,keyword:text(200)},['id','category_id','expected_updated_at'])
for(const action of ['categorize','move','delete','restore'])write('bulk_'+action,'Масові операції: '+action,'Apply one action atomically to explicitly selected transaction IDs. Supply the exact updated_at for every ID.',{ids:{type:'array',items:uuid,minItems:1,maxItems:500},versions:{type:'object',additionalProperties:timestamp},...(action==='categorize'?{category_id:uuid}:{}),...(action==='move'?{account_id:uuid}:{})},['ids','versions',...(action==='categorize'?['category_id']:[]),...(action==='move'?['account_id']:[])],'bulk_'+action,['delete','restore','move'].includes(action))
write('make_transfer','Позначити власний переказ','Convert an operation to an own-account transfer. Match the other bank leg when present; never double count. For cross-currency transfers give both actual amounts.',{id:uuid,expected_updated_at:timestamp,source_account_id:uuid,destination_account_id:uuid,source_amount:money,received_amount:money,match_id:nullable(uuid),match_updated_at:nullable(timestamp),confirm_missing:bool},['id','expected_updated_at','source_account_id','destination_account_id','source_amount','received_amount'],'make_transfer',true)
write('resolve_pair','Об’єднати дубль або переказ','Combine explicitly chosen records after checking the source evidence. Equal amounts alone do not prove a duplicate.',{keep_id:uuid,remove_id:uuid,is_transfer:bool,keep_updated_at:timestamp,remove_updated_at:timestamp},['keep_id','remove_id','is_transfer','keep_updated_at','remove_updated_at'],'resolve_pair',true)
write('undo_resolution','Скасувати об’єднання','Undo a resolution only when the underlying records have not changed.',{id:uuid},['id'],'undo_resolution',true)
write('confirm_balance','Звірити фактичний залишок','Confirm the bank/cash balance using the account ledger_version and balance_anchor_at from the most recent read. Negative credit-card debt is supported. Executes directly when write access is granted.',{account_id:uuid,value:{type:'string',minLength:1,maxLength:60,description:'Signed balance e.g. -41116,45. Empty is not zero.'},ledger_version:{type:'integer',minimum:0},anchor_at:timestamp,note:text(200)},['account_id','value','ledger_version','anchor_at'],'confirm_balance',true)
write('undo_balance','Скасувати останню звірку','Undo only a safe latest confirmation with no subsequent financial changes.',{id:uuid},['id'],'undo_balance',true)
write('cancel_import','Скасувати імпорт виписки','Remove the effects of this import using the same guarded cancellation as the UI.',{id:uuid},['id'],'cancel_import',true)
write('move_import','Виправити рахунок імпорту','Move all active entries in an import to the correct account. Read get_import first and use its entries_version. Complex transfer legs may require individual correction.',{id:uuid,account_id:uuid,expected_version:version},['id','account_id','expected_version'],'move_import',true)
write('create_account','Додати рахунок','Create a bookkeeping account, not a real bank account. opening_balance is today’s signed snapshot; debt is negative.',{values:values({...accountFields,opening_balance:signed},['name','type','currency','opening_balance'])},['values'])
write('update_account','Налаштувати рахунок','Change bookkeeping account metadata. Cannot directly overwrite current balance or its anchor.',{id:uuid,expected_version:version,values:values(accountFields)},['id','expected_version','values'])
write('archive_account','Архівувати рахунок','Archive an account without deleting transaction history.',{id:uuid,expected_version:version},['id','expected_version'],'archive_account',true)
for(const [name,fields] of [['category',categoryFields],['rule',ruleFields]] as const){
 write('create_'+name,'Створити '+name,'Create a family '+name+'.',{values:values(fields,name==='category'?['name','type']:['name','category_id','description_contains'])},['values'])
 write('update_'+name,'Редагувати '+name,'Update using _version from the most recent read.',{id:uuid,expected_version:version,values:values(fields)},['id','expected_version','values'])
 write('delete_'+name,'Видалити '+name,'Delete as instructed by the user. Related records can block deletion.',{id:uuid,expected_version:version},['id','expected_version'],'delete_'+name,true)
}
write('update_settings','Особисті налаштування','Update only the connected user’s preferences. Does not grant AI permissions.',{expected_version:version,values:values({display_currency:currency,safety_buffer_days:{type:'integer',minimum:1,maximum:365},default_account_id:nullable(uuid),favorite_account_ids:{type:'array',items:uuid,maxItems:100},import_reminder_enabled:bool,import_reminder_weekday:{type:'integer',minimum:0,maximum:6},import_reminder_dismissed:bool})},['expected_version','values'])
write('save_loan','Налаштувати кредит','Create or update the loan profile. Supply existing _version when updating. Does not infer current principal from old schedules.',{account_id:uuid,expected_version:version,values:values(loanFields)},['account_id','values'])
write('pay_loan','Записати платіж кредиту','Record the full payment as a household expense linked to a loan. Loan balance is manually confirmed and is not reduced automatically. Pass transaction_id and expected_updated_at to complete a plan or link an existing payment, never create a duplicate. Credit-card repayment remains a transfer. A schedule never generates transactions.',{account_id:uuid,values:values({payment_account_id:uuid,transaction_id:nullable(uuid),installment_id:nullable(uuid),expected_updated_at:timestamp,date,total:money},['payment_account_id','date','total']),duplicate_resolution:duplicateResolution},['account_id','values'],'pay_loan',true)
write('set_period','Відкрити або закрити місяць','Close/reopen an accounting month as instructed by the user. Existing closed-month protections remain enforced.',{month:date,closed:bool},['month','closed'],'set_period',true)

export function validate(schema:Schema,value:unknown,path='arguments'):void {
 const types=Array.isArray(schema.type)?schema.type:[schema.type]
 if(value===null){if(types.includes('null'))return;throw new Error(path+': null is not allowed')}
 const type=typeof value==='number'&&Number.isInteger(value)&&types.includes('integer')?'integer':Array.isArray(value)?'array':typeof value
 if(!types.includes(type))throw new Error(path+': expected '+types.join(' or '))
 if(schema.enum&&!schema.enum.some(v=>v===value))throw new Error(path+': unsupported value')
 if(type==='string'){
  const s=value as string;if((schema.minLength!==undefined&&s.length<schema.minLength)||(schema.maxLength!==undefined&&s.length>schema.maxLength))throw new Error(path+': invalid length')
  if(schema.pattern&&!new RegExp(schema.pattern).test(s))throw new Error(path+': invalid format')
  if(schema.format==='uuid'&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s))throw new Error(path+': UUID required')
  if(schema.format==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s))throw new Error(path+': valid calendar date required')
  if(schema.format==='date-time'&&(!/^\d{4}-\d{2}-\d{2}T/.test(s)||!/(Z|[+-]\d{2}:\d{2})$/.test(s)||!Number.isFinite(Date.parse(s))))throw new Error(path+': timestamp with timezone required')
 }
 if(type==='number'||type==='integer'){const n=value as number;if(!Number.isFinite(n)||(schema.minimum!==undefined&&n<schema.minimum)||(schema.maximum!==undefined&&n>schema.maximum))throw new Error(path+': number outside limits');if(schema.multipleOf===0.01&&Math.abs(n*100-Math.round(n*100))>0.001)throw new Error(path+': at most two decimal places')}
 if(type==='array'){const a=value as unknown[];if((schema.minItems!==undefined&&a.length<schema.minItems)||(schema.maxItems!==undefined&&a.length>schema.maxItems))throw new Error(path+': invalid number of items');a.forEach((v,i)=>validate(schema.items!,v,path+'['+i+']'))}
 if(type==='object'){
  const o=value as Record<string,unknown>;for(const key of schema.required||[])if(!(key in o))throw new Error(path+'.'+key+': required')
  if(Object.keys(o).length>1000)throw new Error(path+': too many fields')
  for(const [key,v]of Object.entries(o)){if(['__proto__','constructor','prototype'].includes(key))throw new Error('Unsafe property');const child=schema.properties?.[key]||(typeof schema.additionalProperties==='object'?schema.additionalProperties:null);if(child)validate(child,v,path+'.'+key);else if(schema.additionalProperties!==true)throw new Error(path+'.'+key+': unknown field')}
 }
}
export function toolMetadata(tool:Tool){return {name:tool.name,title:tool.title,description:tool.description,inputSchema:tool.inputSchema,outputSchema:{type:'object',properties:{ok:{type:'boolean'},data:{}},required:['ok'],additionalProperties:false},annotations:{readOnlyHint:tool.readOnly,destructiveHint:!!tool.destructive,openWorldHint:false,idempotentHint:true},securitySchemes:[{type:'oauth2',scopes:['email']}],_meta:{securitySchemes:[{type:'oauth2',scopes:['email']}]}}}
