
'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import Link from 'next/link'
import {ShieldCheck,ArrowRight,LockKeyhole} from 'lucide-react'
import {createClient} from '@/lib/supabase/client'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {Checkbox} from '@/components/ui/checkbox'
export function AiConsent({authorizationId}:{authorizationId:string}){
 const router=useRouter(),[details,setDetails]=useState<any>(null),[write,setWrite]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let alive=true;(async()=>{if(!authorizationId)throw new Error('Посилання на підключення неповне. Додайте Forma в ChatGPT або Claude ще раз.');const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user){router.replace('/auth/login?returnUrl='+encodeURIComponent('/oauth/consent?authorization_id='+authorizationId));return}const {data,error}=await db.auth.oauth.getAuthorizationDetails(authorizationId);if(error)throw error;if(data&&'redirect_url'in data){if(typeof data.redirect_url!=='string'||!data.redirect_url)throw new Error('Сервіс авторизації не повернув адресу продовження');window.location.assign(data.redirect_url);return}if(alive)setDetails(data)})().catch(e=>{if(alive)setError(e.message||'Не вдалося відкрити запит підключення')});return()=>{alive=false}},[authorizationId,router])
 async function decide(approve:boolean){setBusy(true);setError('');try{const db=createClient();if(approve){const {error}=await db.rpc('finance_mcp_grant',{p_authorization:authorizationId,p_write:write});if(error)throw error}const result=approve?await db.auth.oauth.approveAuthorization(authorizationId):await db.auth.oauth.denyAuthorization(authorizationId);if(result.error)throw result.error;if(result.data?.redirect_url)window.location.assign(result.data.redirect_url);else throw new Error('Сервіс авторизації не повернув адресу продовження')}catch(e){setError(e instanceof Error?e.message:'Підключення не виконано');setBusy(false)}}
 return <main className="relative flex min-h-[100dvh] items-center justify-center overflow-x-hidden bg-[var(--bg-primary)] px-4 py-[calc(2rem+env(safe-area-inset-top))]"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top,var(--ambient-glow),transparent_65%)]"/><div className="relative w-full max-w-md"><Link href="/" className="mb-6 inline-flex min-h-11 items-center gap-2 font-space-grotesk text-xl font-semibold"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[var(--accent-primary)] text-[var(--text-inverse)]">F</span>Forma</Link><Card><ShieldCheck className="mb-4 h-9 w-9 text-[var(--accent-primary)]"/><h1 className="text-2xl font-semibold leading-tight">Доступ до сімейних фінансів</h1>{details?<><p className="mt-3 break-words text-secondary"><strong className="text-primary">{details.client?.name||'AI-клієнт'}</strong> просить підключення до вашого акаунта Forma.</p><div className="my-5 space-y-3 rounded-2xl border border-primary p-4"><div className="flex items-start gap-3"><LockKeyhole className="mt-0.5 h-5 w-5 shrink-0 text-[var(--accent-primary)]"/><div><p className="font-medium">Читання фінансів вашої сім’ї</p><p className="mt-1 text-sm text-secondary">Рахунки, операції, кредити, звіти та прогнози.</p></div></div><div className="border-t border-primary pt-2"><Checkbox checked={write} onChange={e=>setWrite(e.target.checked)}>Також дозволити додавання й зміни</Checkbox><p className="ml-9 text-xs leading-5 text-secondary">AI зможе одразу виконувати ваші доручення, зокрема імпорт, звірки, зміни кредитів і видалення записів, без додаткових підтверджень у Forma.</p></div></div><p className="text-sm leading-6 text-secondary">Дані, які прочитає AI, передаватимуться цьому сервісу. Пароль і банківські ключі не передаються. Дозвіл діє до 90 днів; його можна відкликати будь-коли.</p><details className="mt-3 text-xs text-secondary"><summary className="min-h-11 cursor-pointer py-3">Адреса повернення й технічні дозволи</summary><p className="break-all">{details.redirect_uri}</p><p className="mt-2">OAuth: {details.scope||'email'}. Фінансові дозволи визначаються вашим вибором вище.</p></details></>:!error?<p className="py-6 text-secondary" role="status">Перевіряємо підключення…</p>:null}{error&&<p role="alert" className="my-4 rounded-xl border border-[var(--accent-error)]/30 p-3 text-sm text-[var(--accent-error)]">{error}</p>}{details&&<div className="mt-5 grid grid-cols-2 gap-3"><Button variant="secondary" disabled={busy} onClick={()=>decide(false)}>Відхилити</Button><Button disabled={busy} onClick={()=>decide(true)}>{busy?'Підключення…':'Дозволити'}<ArrowRight className="ml-2 h-4 w-4"/></Button></div>}</Card><p className="mt-4 text-center text-xs text-secondary">Лише облік. AI не може переказувати гроші в банку.</p></div></main>
}