'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {Bell,X} from 'lucide-react'
import {Card,CardTitle} from '@/components/ui/Card'
import {Button} from '@/components/ui/Button'
import {Select} from '@/components/ui/select'
import {useSettings,useUpdateSettings,useImportBatches} from '@/hooks/use-finance'
import {createClient} from '@/lib/supabase/client'
import {useToast} from '@/components/ui/toast'
export function ImportReminderSuggestion(){
 const {data:settings}=useSettings(),{data:batches=[]}=useImportBatches(),update=useUpdateSettings()
 if(!settings||settings.importReminderEnabled||settings.importReminderDismissed||!batches.some(b=>(b as unknown as {created_by:string}).created_by===settings.userId))return null
 return <aside className="import-reminder-nudge"><Bell size={19}/><Link href="/settings#import-reminders"><strong>Нагадувати про виписки?</strong><span>Раз на тиждень, лише за вашою згодою</span></Link><button type="button" className="finance-icon-button" aria-label="Не нагадувати зараз" disabled={update.isPending} onClick={()=>update.mutate({importReminderDismissed:true})}><X size={17}/></button>{update.isError&&<p role="alert">Не вдалося зберегти вибір. Спробуйте ще раз.</p>}</aside>
}
export function ImportReminderCard(){
 const {data:settings}=useSettings(),update=useUpdateSettings(),toast=useToast(),[busy,setBusy]=useState(false),[supported,setSupported]=useState(false),[iosNeedsInstall,setIosNeedsInstall]=useState(false),[permission,setPermission]=useState('default'),[weekday,setWeekday]=useState('1')
 useEffect(()=>{const standalone=window.matchMedia('(display-mode: standalone)').matches||(navigator as Navigator&{standalone?:boolean}).standalone;const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);setIosNeedsInstall(!!ios&&!standalone);setSupported('serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window);setPermission('Notification'in window?Notification.permission:'unsupported')},[])
 useEffect(()=>{if(settings)setWeekday(String(settings.importReminderWeekday??1))},[settings])
 async function enable(){setBusy(true);try{const answer=await Notification.requestPermission();setPermission(answer);if(answer!=='granted')throw new Error('Дозвіл не надано. Нагадування не ввімкнено.');const db=createClient(),{data:key,error}=await db.rpc('finance_push_public_key');if(error||!key)throw new Error('Не вдалося отримати ключ push');await navigator.serviceWorker.register('/sw.js',{scope:'/',updateViaCache:'none'});const registration=await navigator.serviceWorker.ready;const bytes=Uint8Array.from(atob(String(key).replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const sub=await registration.pushManager.getSubscription()||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});const json=sub.toJSON();const saved=await db.rpc('finance_save_push',{p_endpoint:sub.endpoint,p_p256dh:json.keys?.p256dh,p_auth:json.keys?.auth,p_enabled:true});if(saved.error)throw saved.error;await update.mutateAsync({importReminderEnabled:true,importReminderWeekday:Number(weekday),importReminderDismissed:true});toast.success('Push-нагадування ввімкнено')}catch(e){toast.error('Нагадування не ввімкнено',e)}finally{setBusy(false)}}
 async function saveDay(){setBusy(true);try{await update.mutateAsync({importReminderWeekday:Number(weekday)});toast.success('День нагадування збережено')}catch(e){toast.error('Не вдалося зберегти день',e)}finally{setBusy(false)}}
 async function test(){setBusy(true);try{const {data,error}=await createClient().functions.invoke('import-reminders',{body:{action:'test'}});if(error)throw error;if(!data.delivered)throw new Error(data.message);toast.success('Тест передано push-сервісу','Перевірте сповіщення на цьому пристрої.')}catch(e){toast.error('Тест не доставлено',e)}finally{setBusy(false)}}
 return <Card id="import-reminders"><CardTitle className="mb-3">Нагадування про виписки</CardTitle><p className="mb-4 text-sm text-secondary">Лише за вашою згодою. Раз на тиждень уранці за київським часом. Без email і без фінансових сум на екрані блокування.</p><div className="space-y-4"><Select label="День нагадування" value={weekday} onChange={e=>setWeekday(e.target.value)} options={[{value:'1',label:'Понеділок'},{value:'2',label:'Вівторок'},{value:'3',label:'Середа'},{value:'4',label:'Четвер'},{value:'5',label:'П’ятниця'},{value:'6',label:'Субота'},{value:'0',label:'Неділя'}]}/>{iosNeedsInstall&&<p className="text-sm text-[var(--accent-warning)]">На iPhone спочатку відкрийте сайт у Safari, натисніть «Поділитися» → «На початковий екран». Відкрийте Forma з цієї іконки та ввімкніть push тут. Потрібна iOS 16.4 або новіша.</p>}{!supported&&!iosNeedsInstall&&<p className="text-sm text-secondary">Цей браузер не підтримує push. Відкрийте встановлену PWA або сумісний браузер.</p>}{permission==='denied'&&<p className="text-sm text-[var(--accent-warning)]">Сповіщення заблоковані. Дозвольте їх у налаштуваннях сайту або iPhone, потім поверніться сюди.</p>}<p role="status" className="text-sm">{settings?.importReminderEnabled?'Нагадування ввімкнені для вашого облікового запису.':'Нагадування вимкнені.'}</p><div className="reminder-actions">{settings?.importReminderEnabled&&<Button disabled={busy||update.isPending||weekday===String(settings.importReminderWeekday??1)} onClick={saveDay}>Зберегти день</Button>}<Button variant={settings?.importReminderEnabled?'secondary':'primary'} disabled={!supported||iosNeedsInstall||busy||!settings} onClick={enable}>{busy?'Зачекайте…':settings?.importReminderEnabled?'Підключити цей пристрій':'Увімкнути нагадування'}</Button>{settings?.importReminderEnabled&&<><Button variant="secondary" disabled={busy} onClick={test}>Тестове сповіщення</Button><Button variant="ghost" disabled={busy||update.isPending} onClick={async()=>{try{await update.mutateAsync({importReminderEnabled:false});toast.success('Нагадування вимкнено на всіх ваших пристроях')}catch(error){toast.error('Не вдалося вимкнути',error)}}}>Вимкнути нагадування</Button></>}</div><p className="text-xs text-muted">Дозвіл потрібен окремо на кожному пристрої. Доставка залежить від налаштувань системи, інтернету та режиму фокусування.</p></div></Card>
}